# /**
#  * Copyright (c) Connexta
#  *
#  * <p>This is free software: you can redistribute it and/or modify it under the terms of the GNU
#  * Lesser General Public License as published by the Free Software Foundation, either version 3 of
#  * the License, or any later version.
#  *
#  * <p>This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
#  * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  * GNU Lesser General Public License for more details. A copy of the GNU Lesser General Public
#  * License is distributed along with this program and can be found at
#  * <http://www.gnu.org/licenses/lgpl.html>.
#  */
openapi: 3.0.2

info:
  version: ${project.version}
  title: ${project.name}
  description: >
    A sample API that enables us to define common models and specification elements that can be
    reuse in other APIs/
  contact:
    name: Connexta
  license:
    name: GNU Lesser General Public License
    url: 'http://www.gnu.org/licenses/lgpl.html'

servers:
  - url: ${rest.server.url}

paths:
  /sample:
    parameters:
      - $ref: 'commons.yaml#/components/parameters/AcceptVersion'
      - $ref: 'commons.yaml#/components/parameters/Echo'
    post:
      summary: Sample endpoint.
      description: >
        Sample endpoint.
      operationId: sample
      tags:
        - sample
      responses:
        '200':
          $ref: 'commons.yaml#/components/responses/OK'
        '307':
          $ref: 'commons.yaml#/components/responses/TemporaryRedirect'
        '308':
          $ref: 'commons.yaml#/components/responses/PermanentRedirect'
        '400':
          $ref: 'commons.yaml#/components/responses/BadRequest'
        '401':
          $ref: 'commons.yaml#/components/responses/Unauthorized'
        '501':
          $ref: 'commons.yaml#/components/responses/NotImplemented'
        default:
          $ref: 'commons.yaml#/components/responses/DefaultError'
