/**
 * Copyright (c) Connexta
 *
 * <p>This is free software: you can redistribute it and/or modify it under the terms of the GNU
 * Lesser General Public License as published by the Free Software Foundation, either version 3 of
 * the License, or any later version.
 *
 * <p>This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details. A copy of the GNU Lesser General Public
 * License is distributed along with this program and can be found at
 * <http://www.gnu.org/licenses/lgpl.html>.
 */
package com.connexta.spring.error;

import java.util.Collections;
import java.util.List;

/**
 * Exceptions can implement this interface to provide detail information that should be added to
 * error responses that are automatically generated by Spring or extends the {@link
 * DetailedResponseStatusException} exception directly. They could also simply annotate their
 * exceptions with {@link com.connexta.spring.annotation.DetailedResponseStatus}.
 */
public interface Detailable {
  /**
   * Gets a more specific code for the error that should be included in the resulting error message
   * (defaults to <code>-1</code>).
   *
   * @return a more specific code for the error or <code>-1</code> if no specific code is available
   */
  default int getCode() {
    return -1;
  }

  /**
   * Gets additional details information about the error that should be included in the resulting
   * error message (defaults to none).
   *
   * @return additional information about the error
   */
  default List<String> getDetails() {
    return Collections.emptyList();
  }
}
